CREATE SCHEMA 'produtos' DEFAULT CHARACTER SET utf-8;

CREATE TABLE PRODUTO (
	ID int NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
	ID_PRODUTO_PAI int FOREIGN KEY REFERENCES PRODUTO(ID),
	PRIMARY KEY (ID)
);

CREATE TABLE IMG_PRODUTO (
	ID int NOT NULL PRIMARY KEY,
	IMAGEM BLOB,
	TIPO VARCHAR(50),
	ID_PRODUTO int FOREIGN KEY REFERENCES PRODUTO(ID)
);
